### ISSUE TITLE
Timeout while loading external DTD

### ISSUE THREAD

**Issue by Relax594** [uli-weltersbach/XPathTools#30]
XmlRepository.TryParseXml is getting a timeout while loading this external DTD from my given xml.

We are using a Proxy in our company, maybe that is causing the issue but idk

`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">`

**Comment by uli-weltersbach** [comment]
Hi Dominik,

I'm looking into the issue, which doesn't seem to be caused by your proxy.
Note to self: https://msdn.microsoft.com/en-us/library/aa302284.aspx

**Comment by uli-weltersbach** [comment]
Hi @Relax594 

The issue should be resolved in v5.2.1.
Please let me know if it works out for you.

**Comment by Relax594** [comment]
That did not fix it as i get a System.IO.DirectoryNotFoundException now. Looks like he is trying to search that DTD on my local pc "C:/Users/dotel/Desktop/-//W3C//DTD XHTML 1.0 Strict//EN" now

**Comment by Relax594** [comment]
I've uploaded a txt file, you need to change the file extension to .xml. After that open that file in Visual Studio and try to run your plugin.
[test.txt](https://github.com/uli-weltersbach/XPathTools/files/2547293/test.txt)

This is the exception i'm getting (it's german but i think you get the point :)).
![exception](https://user-images.githubusercontent.com/22765758/47983874-0321c200-e0d5-11e8-98af-ab01e42a61d9.PNG)

**Comment by uli-weltersbach** [comment]
I can't reproduce the behavior your describing: https://www.screencast.com/t/WjOnu3HqRAu

Could you please provide your debug settings, particularly the "Just my code" setting?

![image](https://user-images.githubusercontent.com/1416006/47984238-49c3ec00-e0d6-11e8-95f7-16e4c29c55a0.png)

![image](https://user-images.githubusercontent.com/1416006/47984242-4fb9cd00-e0d6-11e8-84dd-e9bd27c73452.png)

**Comment by uli-weltersbach** [comment]
I'll restate my previous comment:

**The exception is part of the `XmlUrlResolver` control flow.**
The `XmlReader` **needs** the `XmlUrlResolver` to throw an exception.

**Comment by Relax594** [comment]
My Debug Settings are like yours. I will make a screencast for you, give me a second

**Comment by Relax594** [comment]
I'm using some of your classes inside my own plugin but the core should be the same and make no difference. I'm not even into getting the XPATH, it happens while loading the XML on TextViewCreated


![unbenannt](https://user-images.githubusercontent.com/22765758/47986414-f608d100-e0dc-11e8-9d7a-216d4564625c.png)

![unbenannt3](https://user-images.githubusercontent.com/22765758/47986461-22bce880-e0dd-11e8-9fef-739989a05144.PNG)

![unbenannt2](https://user-images.githubusercontent.com/22765758/47986430-0456ed00-e0dd-11e8-9677-e7359b58c97d.PNG)

and then we end up back again in GetEntity with the exception.

**Comment by uli-weltersbach** [comment]
You want me to help your debug *your own* VS Extension, which uses some of the code from the XML Tools extension?

**Comment by Relax594** [comment]
I linked your classes inside my extension, so it uses all your methods and workflow. So there is basicly no difference.

**Comment by uli-weltersbach** [comment]
If you run into the exception during debugging, you can *ignore it* because *the exception is expected and required by the .NET Framework XML classes* (I'm stating this for the 3rd time now).

What happens when you click "Continue" in the debugger and try to use *your* extension?

I'm not sure I can assist you further, without getting my hands on *your* extension.

**Comment by Relax594** [comment]
>  (I'm stating this for the 3rd time now).

Then I missunderstood you, sorry for that.

As i said, its working fine if i click continue^^ It is just that loading exception i got, but if that is expected and required than i totaly missunderstood you and i'm sorry for taking your time!

**Comment by uli-weltersbach** [comment]
Sorry if I was unclear about it, happy I could help.
